### ISSUE TITLE
Add Support for len(CollectionResource)

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#102]
Right now, calling len() on any collection resource results in an invalid credentials error, for instance:

```python
>>> from stormpath.client import Client
>>> from stormpath.resources.account import Account
>>> client = Client(api_key_file_location='apiKey.properties')
>>> for app in c.applications:
>>>     print app.name
>>> results = app.accounts.search({'username': 'rdegges'})
>>> len(results)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stormpath/resources/base.py", line 433, in __len__
    self._ensure_data()
  File "stormpath/resources/base.py", line 270, in _ensure_data
    data = self._store.get_resource(self.href, params=params)
  File "stormpath/data_store.py", line 122, in get_resource
    data = self.executor.get(href, params=params)
  File "stormpath/http.py", line 91, in get
    return self.request('GET', url, params=params)
  File "stormpath/http.py", line 81, in request
    raise Error(r.json(), http_status=r.status_code)
stormpath.error.Error: Authentication with a valid API Key is required.
```

It looks like we're not properly handling this.

FYI -- we recently added a new 'size' attribute to all CollectionResource responses.

For instance, if you query the rest API for accounts on an application, you'll see we now return a 'size' property (which is an integer), that reflects how many total items are in the collection.

This could be really useful here =)

**Comment by denibertovic** [comment]
Hi @rdegges . Quick question. How does the newly added 'size' property deal with slicing?

For example:

     # should this return 20 or the full size (assuming the full size is let's say 100)
     gs = app.groups[:20]
     len(gs)  

Obviously if there are less than 20 entries in the collection then it will return the exact number.

**Comment by rdegges** [comment]
This is working beautifully now.
