### ISSUE TITLE
InvalidAudienceError in Application.handle_id_site_callback

### ISSUE THREAD

**Issue by skolsuper** [stormpath/stormpath-sdk-python#110]
When the jwt token from the url is decoded by jwt.decode, it throws an invalid audience error if there is an 'aud' field in the payload but no audience passed in:
```
def decode(jwt, key='', verify=True, **kwargs):
    payload, signing_input, header, signature = load(jwt)

    if verify:
        verify_signature(payload, signing_input, header, signature, key,
                         **kwargs)

    return payload
```
...
```
def verify_signature(payload, signing_input, header, signature, key='',
                     verify_expiration=True, leeway=0, audience=None,
                     issuer=None):
    ...
    if 'aud' in payload:
        audience_claims = payload['aud']
        if isinstance(audience_claims, string_types):
            audience_claims = [audience_claims]
        if not isinstance(audience_claims, list):
            raise InvalidAudienceError('Invalid claim format in token')
        if any(not isinstance(c, string_types) for c in audience_claims):
            raise InvalidAudienceError('Invalid claim format in token')
        if audience not in audience_claims:
            raise InvalidAudienceError('Invalid audience')
```

The stormpath application handle_id_site_callback function doesn't pass in an audience kwarg to jwt.decode, so if there is an 'aud' in the payload from stormpath (and currently there is, it contains my stormpath api id) it will never verify. I think this has been overlooked since the exception goes uncaught:

stormpath.resources.application.py:
```
def handle_id_site_callback(self, url_response):
    ...
    api_key_secret = self._client.auth.secret

    # validate signature
        try:
            decoded_data = jwt.decode(jwt_response, api_key_secret)
        except (jwt.DecodeError, jwt.ExpiredSignature):
            return None
    ...
```

I can fix it for my site by modifying application.py to this:

```
        api_key_secret = self._client.auth.secret
        api_key_id = self._client.auth.id

        # validate signature
        try:
            decoded_data = jwt.decode(jwt_response, api_key_secret, audience=api_key_id)
        except (jwt.DecodeError, jwt.ExpiredSignature):
            return None
```

but heroku for some reason refuses to install my fork and defaults to using the package, so at the minute my application can't handle logins and logouts.

**Comment by rdegges** [comment]
Thanks for reporting this. I'm taking a closer look now.

I'm not that familiar with how this was implemented, so will take a little bit longer than normal ><

**Comment by denibertovic** [comment]
@rdegges this is odd because it was working before. We even have live tests that were passing before. I will investigate what's causing this.

**Comment by denibertovic** [comment]
@rdegges @skolsuper This is because of the constrains on pyjwt versions we have in setup.py (it's pretty liberal) meaning that the newest version will get installed, and a new version introduced this change. I fixed it in #109

**Comment by denibertovic** [comment]
@skolsuper tnx for your help on this! :+1:

**Comment by rdegges** [comment]
I'm prepping a release right now for this. Will be closed out shortly =)

**Comment by skolsuper** [comment]
Thanks very much guys.

In case any time travellers that find this thread are having the same problems with heroku, I think it was because django-stormpath names this as a dependency, which causes pip to fetch it from the package repository. Then when it gets to the specified git version in requirements.txt, pip ignores it unless the version number is higher.

**Comment by rdegges** [comment]
Ok! This is all pushed and released. Sorry for the delay!
