### ISSUE TITLE
memcache retrievals fail to parse because CacheEntry expects dict but gets tuple(dict)

### ISSUE THREAD

**Issue by stauffec** [stormpath/stormpath-sdk-python#116]
In testing if I'm really reducing the number of http requests to storm path, I noticed that memcache store was silently failing because when it was returning results, it was wrapping the account value in a tuple:

If the code in memcache_store  is left as:

    def __getitem__(self, key):
.....
        return CacheEntry.parse(entry)

CacheEntry throws an error because it tries to execute data['value'].
*** AttributeError: 'tuple' object has no attribute 'get'

It looks like the memcache.get call returns a dictionary wrapped in a tuple ({})
I got it to work by having the memcache class return:

       return CacheEntry.parse(entry[0])

**Comment by denibertovic** [comment]
I'm quite sure this was tested manually and covered with tests. My best guess is that the memcached python library's API changed with a newer version.

**Comment by rdegges** [comment]
Fixed and released!
