### ISSUE TITLE
Group checking doesn't use the cache

### ISSUE THREAD

**Issue by dourvaris** [stormpath/stormpath-sdk-python#117]
`user.has_group('admin)` doesn't seem to use the cache at all, likewise `user.has_group(group_object)` also seems to make an API request whereas the docs say it won't.

The offending section seems to be here https://github.com/stormpath/stormpath-sdk-python/blob/master/stormpath/resources/account.py#L221 

```python
        for g in self.groups.query(name=group.name):
            if g.name == group.name:
                return True
```

**Comment by rdegges** [comment]
We'll look into this! Thanks so much for the report! <33

**Comment by avojnovicDk** [comment]
I am not sure if this is the part @dourvaris is referring to:
> Passing in a :class:`stormpath.resources.group.Group` object will always be the quickest way to check a Group's membership, since it doesn't require any additional API calls.

, but if it is and I am interpreting it correctly, it is only saying that if you pass a Group href, name or some other resolvable (as opposed to `stormpath.resources.group.Group`), it will make additional API calls (to resolve the Group). This line:
```
for g in self.groups.query(name=group.name):
```
will always make an API call and I cannot find where the docs say it won't.

**Comment by avojnovicDk** [comment]
I experimented with different Group resolvables and this is what I found:
If you use ```stormpath.resources.group.Group```, there will be no calls made until it reaches line
```
for g in self.groups.query(name=group.name):
```
For all the other cases, it will make an additional API call, even if you pass the Group href (because it accesses ``group.name`` to check if group is valid or not).

**Comment by rdegges** [comment]
This is actually correct, @avojnovicDk .

To properly take advantage of caching here you'll need to lookup the group yourself, then pass that object into your queries.
