### ISSUE TITLE
createdAt / modifiedAt properties and queries

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-python#136]
createdAt and modifedAt has been added for all resources in Stormpath.  Need the ability to read / query via the python SDK

As a developer, I want to get all accounts that were created in the last 5 min, so I can update the information I store in my DB
As a developer, I want to get all groups that were modified in between 1/1/2015 and 1/7/2015, so I can audit the changes
As a developer, I want to get all directories that were modified in the last 5 min, so I can update the information I store in my DB

**Comment by rdegges** [comment]
Closing this as it's been merged in and released.
