### ISSUE TITLE
Add Convenience Reference: Application.directories

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#148]
Currently, if you have an Application object, you can say:

```python
>>> for group in application.groups:
>>>    ...
>>> for mapping in application.account_store_mappings:
>>>    ...
```

But there's currently no way to say:

```python
>>> for directory in application.directories:
>>>    ...
```

I think this would be a nice convenience attribute to add, as it'll simplify things for users who want to quickly iterate over DIRECTORIES only.

@avojnovicDk would ya include this in the next PR? Thanks a ton ^^ <33

**Comment by lhazlewood** [comment]
@rdegges we need to talk about this first.  Our SDKs should be feature compliant. Ping @robertjd @omgitstom

**Comment by lhazlewood** [comment]
Note that the suggested method could be confusing: what is an application's directories collection?  Groups is an aggregate view across all associated account stores.  There is no parallel for Directories.  Further, it might add confusion as to what is a Directory vs an Account Store.  @avojnovicDk please do not implement this until we've had a chance to discuss.
