### ISSUE TITLE
Can not iterate through a collection and delete resources

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-python#151]
When iterating through a collection, and deleting resources the pagination gets messed up and not all resources are deleted in the collection

**Comment by avojnovicDk** [comment]
I think this is OK because you shouldn't remove items while iterating: http://stackoverflow.com/questions/1352885/remove-elements-as-you-traverse-a-list-in-python .
Suggested workaround works in this case, too. This:
```
for acc in list(app.accounts):
    acc.delete()
```
will always delete all accounts in the app.

**Comment by rdegges** [comment]
So, after talking about this with @avojnovicDk and @omgitstom, I think we've come to the conclusion that for now, the above method is the best way to handle this =)

I think in the long run we'll improve our pagination API to make stuff like this simpler.
