### ISSUE TITLE
Automatically Fetch Password Policy Attributes

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#170]
Right now, if you want to pragmatically get a list of a Directory's attributes, you have to do some nasty magic.

Here's an example of what's going on:

```python
>>> dict(directory.password_policy.strength)
{u'href': 'xxx'}
```

By calling `dict()` on this attribute, we should automatically fetch the linked attributes so that the dict call returns ALL key / values available -- not just the href.

@avojnovicDk can you implement this one in a similar fashion to the directory stuff a few weeks back?

**Comment by avojnovicDk** [comment]
Hey @rdegges, that fix I made wasn't for the directory only, but for all resources with DictMixin (and PasswordStrength is one of those). So, if you use latest develop, you should get all key/value pairs. I checked and it works. Can you confirm?

**Comment by rdegges** [comment]
D'oh -- I thought I was using develop when I tested this, but I just realized I was on master >.>

This is my bad. I'll cut a release and get this out today because we've got a customer who is being affected.
