### ISSUE TITLE
Unable to Retrieve Tenant from Client

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#172]
We should make it possible for a developer to say:

```python
>>> print client.tenant
```

And get a Tenant object returned. Right now the only way to access the Tenant object is via an Application -- this is super inconvenience.

**Comment by avojnovicDk** [comment]
Actually, this is already possible and you are the one who added this feature: https://github.com/stormpath/stormpath-sdk-python/commit/cbcd29f9457515dc6a6bb32cb10339e19067dda1 .

**Comment by rdegges** [comment]
Hmm... I have no idea how I missed this ><

Sorry for bugging ya! I must have been doing something weird in my environment. I just tested this now and... you're 100% right =/

I'm a noob cake.
