### ISSUE TITLE
Issue With Email Saving

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#190]
https://gist.github.com/bq1990/c16a5f7d16584eaa9eeb

Essentially: it looks like updating email addresses fails when custom data is present (oddly).

**Comment by bq1990** [comment]
If custom_data is updated, none of the other account properties are saved: https://gist.github.com/bq1990/eb3bd20655af1cee7ac8

Does custom data require it's own save?

**Comment by rdegges** [comment]
I'll have to do more testing to ensure this is what's actually happening, right now not 100% sure.

**Comment by avojnovicDk** [comment]
I checked this and this is what is happening: before `custom_data` item is set (`user.custom_data['company']='co'`), `custom_data` attribute for that account has to be retrieved. This calls GET method on the account endpoint and then sets all the account attributes the endpoint returned. It will overwrite the attributes you set before you modified `custom_data`. The above PR fixes this bug.

**Comment by rdegges** [comment]
Thanks @avojnovicDk! Just merged this in, will cut a release today.
