### ISSUE TITLE
Custom Data Saving

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#195]
The below is a bug report from a user. @avojnovicDk can you take a look at this?

When I do account.save(), it seems to update even the fields that were not updated. For example, account.custom_data['profile_image'] is not updated, however custom_data is updated to whatever data that's been saved so far.

Scenario - 1) user originally has "cute cate" profile image. 
2) user goes to Stan site, uploads a new profile image , let's call if "ugly dog" pic. -> stormpath console has "ugly dog" pic url. 
3) user goes to Doug site, system updates "last-login" data in custom_data , custom_data["last_login"] = "Doug- App" then, account.save(). 
This action saves all the user-data at Doug to stormpath. With caching, user data is not updated right away from stormpath, account.save() saves old-profile image "cute cat" picture to stormpath 
-> stormpath consol has "cute cat" pic url even though the profile image was changed to "ugly dog pic" at the (2) step.

**Comment by rdegges** [comment]
It looks like the solution here is to force a refresh of custom Data to bypass the cache before calling `account.save()`. This is probably a manual process, until core Stormpath supports webhooks or something similar.

What you might want to do as a workaround is, before you update any user data or set new user data, run:

```
account.custom_data.refresh()
```

This will forcibly pull the latest changes from Stormpath into custom Data, which then gives you a clean slate to work from.

Custom Data updates are always done in a single request with all information present, so there could potentially be edge cases where two separate sites update the same account's custom data concurrently.

**Comment by jamiepc** [comment]
So you are suggesting this,


Account.custom_data.refresh()
Account.custom_data.last_login = "12334534"
Account.custom_data.modified_app  = "kim"
Account.save()

Right?  Let me check if that works with us..

**Comment by rdegges** [comment]
Yes! That should work perfectly @jamiepc. Please let me know if you have any issues with that.

**Comment by rdegges** [comment]
Ok, this is apparently working.

I'm going to close this issue out, and improve our documentation to cover stuff like this in common use cases. I think in general, having good caching documentation which explains why stuff like this is necessary is probably better =)
