### ISSUE TITLE
Python docs for API authentication out of date

### ISSUE THREAD

**Issue by nkwood** [stormpath/stormpath-sdk-python#203]
Don't know if this repository is the right place to raise it, but the [Python Product Guide section on tokens and API authentication](http://docs.stormpath.com/python/product-guide/#using-the-stormpath-sdk-to-authenticate-and-generate-tokens-for-your-api) appears to be incorrect after 406035f6557b51054b12f99fafef3695bd3c4090.

**Comment by avojnovicDk** [comment]
Yes, this is the right place. Thanks, I'll update the docs!

**Comment by avojnovicDk** [comment]
Docs are updated, so I'll close the issue.
