### ISSUE TITLE
release newest version to pip for python3 support

### ISSUE THREAD

**Issue by sirvon** [stormpath/stormpath-sdk-python#205]
can you guys release a version including the python3 support...
I tried to run setup.py and that's even giving me errors.

Can't use this lib in python3.....

very necessary.

**Comment by avojnovicDk** [comment]
Hey @sirvon ! Which Python 3 version do you use and which errors do you get? This SDK supports Python 3.3+.

**Comment by theoegui** [comment]
Huh

**Comment by rdegges** [comment]
@sirvon bump.

**Comment by theoegui** [comment]
Mr. Randall Degges,

My name is Theo
I have a few questions about stormpath and python.

Sincerely,

Theo

**Comment by rdegges** [comment]
Released.
