### ISSUE TITLE
Doc incorrect..

### ISSUE THREAD

**Issue by nehald** [stormpath/stormpath-sdk-python#206]
In the README.md .  You say to create the client class with
`   client = Client(
    api_key_id = STORMPATH_API_KEY_ID,
    api_key_secret = STORMPATH_API_KEY_SECRET,
)`
This is incorrect.

**Comment by theoegui** [comment]
Im sorry.
I wont do it again.
Sincerely,

Theodore

**Comment by nehald** [comment]
Thanks. No prob.  
Take care

nehal

**Comment by theoegui** [comment]
Well...
I would love to hve in debt knowledge of Stormpath its correlation with
Python.
Im truly fascinated by it.

Sincerely ,

Theo Eguia
