### ISSUE TITLE
Need to be able to iterate over tenant groups

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#220]
Our spec allows us to iterate through groups as a top level resource, see: http://docs.stormpath.com/rest/product-guide/#tenant-groups

We should implement this so that users can say:

```python
>>> for group in client.groups:
          print group.name
```

Right now this is an error.

@avojnovicDk please prio this if you can <3

**Comment by avojnovicDk** [comment]
@rdegges, I've made PR for this ^^.

**Comment by rdegges** [comment]
Released.
