### ISSUE TITLE
Using the Python SDK, ID Site callback fails because of very minor clock skew

### ISSUE THREAD

**Issue by exarkun** [stormpath/stormpath-sdk-python#226]
When dispatching a callback to `stormpath.resources.application.Application.handle_id_site_callback`, it's common to encounter a failure in iat verfication:

```
stormpath/resources/application.py:245 in handle_id_site_callback
                jwt_response, api_key_secret, audience=self._client.auth.id,
                algorithms=['HS256'])
        except (jwt.DecodeError, jwt.ExpiredSignature):
jwt/api_jwt.py:75 in decode
           merged_options = merge_dict(self.options, options)
           self._validate_claims(payload, merged_options, **kwargs)

jwt/api_jwt.py:98 in _validate_claims
       if 'iat' in payload and options.get('verify_iat'):
           self._validate_iat(payload, now, leeway)

jwt/api_jwt.py:129 in _validate_iat
        if iat > (now + leeway):
            raise InvalidIssuedAtError('Issued At claim (iat) cannot be in'
                                       ' the future.')
jwt.exceptions.InvalidIssuedAtError: Issued At claim (iat) cannot be in the future.
```

The default iat leeway supplied by the jwt library is 0.  This means that even a tiny bit of clock skew between systems will make the authentication attempt fail.

There doesn't appear to be a good way for applications to adjust this jwt parameter (if that's even a good idea) via the StormPath API since the jwt usage is entirely internal to StormPath.

**Comment by omgitstom** [comment]
@avojnovicDk @rdegges checking with Les, I think the long term solution is going to be to remove iat from the token, in the meantime for a short term fix we should add 2 seconds of leeway to the library

**Comment by rdegges** [comment]
Closing this as we've merged this in and released it in the 2.1.6 release. If you upgrade you'll get the fix.

**Comment by atomicloopzilla** [comment]
Same bug.
I have 2.5 version.
Just started to try this stormpath - wasted time to perform successful request to ID site.
And callback returned invalid jwt.
I understand that this can be a very minor thing.
But your documentation is poor. Support is poor. Code just doesn't work out of the box.
No working samples in internet for python.
Going to switch to Auth0.

**Comment by rdegges** [comment]
Hey @atomicloopzilla, sorry you had a bad experience :( As you can tell from above, this issue is a result of clock skew on the client server(s). It's a tradeoff between security and ECC :(

I promise I'll do my 100% best to get this stuff fixed ASAP to prevent other people from having bad experiences in the future. If you ever wanna talk and vent or anything, feel free to hit me up whenever (work or personal): randall@stormpath.com / r@rdegges.com.

Lots of love!

<33

-R
