### ISSUE TITLE
Missing method shown in API Key management guide

### ISSUE THREAD

**Issue by canni** [stormpath/stormpath-sdk-python#233]
Here: https://docs.stormpath.com/guides/api-key-management/#exchanging-api-keys-for-oauth-20-tokens

Python examples shows usage of `app.authenticate_api` method, but with latests stormpath version from pypi this method is absent on Application object?

**Comment by avojnovicDk** [comment]
Yes, that method has been removed as we are now using `*Authenticator` classes. You can read about them here: http://docs.stormpath.com/python/product-guide/#using-stormpath-to-secure-and-manage-api-services .

And I'll update the docs you linked. Thanks!

**Comment by avojnovicDk** [comment]
The docs are updated, so I'm closing this issue.
