### ISSUE TITLE
Wheel will not install on Raspbian wheezy (python3)

### ISSUE THREAD

**Issue by mattdodge** [stormpath/stormpath-sdk-python#235]
The latest (2.1.6) wheel has some kind of ascii encoding issue that seems to pop up on Raspbian Linux.

```
pip3 install stormpath==2.1.6
```
yields this stack trace:
```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 677, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 645, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 546, in unzip_file
    fp = open(fn, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 61-63: ordinal not in range(128)
```

This command works on OSX and standard Ubuntu. The same error appears on Raspbian for version 2.1.5 so it likely was introduced with that version (2.1.4 works).

**Comment by stefanv** [comment]
This is because @rdegges (AKA Randall :) accidentally rolled conflicted copies of `__init__.py`, `account.py` and `PKG-INFO` into the wheel.

```
$ unzip stormpath-2.1.6-py2.py3-none-any.whl
...
  inflating: stormpath-2.1.6.dist-info/PKG-INFO (Randall’s MacBook Pro's conflicted copy 2015-11-07)  
...
```

**Comment by theoegui** [comment]
Huh
I don't  understand

**Comment by stefanv** [comment]
@ theoegui The wheel contains files with unicode characters in their names (in this case, files created by Dropbox which should not be in the archive).  Pip does not handle this properly, so you have to remove them:  https://github.com/pypa/pip/issues/3038

**Comment by bnaul** [comment]
@rdegges the new releases 2.1.7 and 2.1.8 still have this issue; can you remove the Dropbox conflict files and reupload to PyPI? The error only occurs with pip3, not pip2, which might be why it's been missed so far.
```
root@28f164581de4:/# unzip -l /tmp/pip-cdlfb_ck-unpack/stormpath-2.1.7-py2.py3-none-any.whl
Archive:  /tmp/pip-cdlfb_ck-unpack/stormpath-2.1.7-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      209  2015-11-06 19:44   stormpath/__init__ (Randall’s MacBook Pro's conflicted copy 2015-11-07).py
...
```

```
root@28f164581de4:/# unzip -l /tmp/pip-x5uvp654-unpack/stormpath-2.1.8-py2.py3-none-any.whl
Archive:  /tmp/pip-x5uvp654-unpack/stormpath-2.1.8-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      209  2015-11-06 19:44   stormpath/__init__ (Randall’s MacBook Pro's conflicted copy 2015-11-07).py
...
```

**Comment by rdegges** [comment]
Oh, damn.... I didn't realize that was the issue. I had no idea that was even getting packaged in there. Going to cut a new release without this in a moment.

**Comment by rdegges** [comment]
This should now be working. I've just cut a new x.x.9 release =)

**Comment by bnaul** [comment]
```
root@b2ddee239e79:/# pip install stormpath==2.1.9
...
Installing collected packages: stormpath
Successfully installed stormpath-2.1.9
```
:100: Thanks!

**Comment by rdegges** [comment]
Yeah, I totally missed that somehow =/ I'm going to write a little script to handle removing these files before all future releases as a precaution.

-R

**Comment by stefanv** [comment]
Great, thank you! You may be able to prevent the problem in the future by
adding a MANIFEST file.

**Comment by rdegges** [comment]
@stefanv just updated this. Did some local testing, so it looks like this will prevent any bad stuff from happening in the future =)
