### ISSUE TITLE
Error object fields not accessible

### ISSUE THREAD

**Issue by arunabha** [stormpath/stormpath-sdk-python#236]
I'm trying to authenticate an account following the guidelines at http://docs.stormpath.com/python/product-guide/#application-accounts

My auth code is 

```python
 try:
        result = stormpath_app.authenticate_account(username, password)
        account = result.account
    except Error as re:
        print(re)
        print(re.message)
```

I'm expecting it to print all the fields of `re` then just the message, but instead I'm getting 

```
{u'status': 400, u'developerMessage': u'Login attempt failed because the specified password is incorrect.', u'message': u'Invalid username or password.', u'code': 7100, u'moreInfo': u'http://docs.stormpath.com/errors/7100'}
{u'status': 400, u'developerMessage': u'Login attempt failed because the specified password is incorrect.', u'message': u'Invalid username or password.', u'code': 7100, u'moreInfo': u'http://docs.stormpath.com/errors/7100'}
```

I.e both `print(re)` and `print(re.message)` are printing exactly the same thing !

Any ideas on why this is happening ?

**Comment by arunabha** [comment]
Update. I also paused the program in pdb and inspected `re`, the results are the same

```
(Pdb) whatis re
<class 'stormpath.error.Error'>
(Pdb) p re
Error({u'status': 400, u'developerMessage': u'Login attempt failed because the specified password is incorrect.', u'message': u'Invalid username or password.', u'code': 7100, u'moreInfo': u'http://docs.stormpath.com/errors/7100'},)
(Pdb) p re.status
400
(Pdb) p re.code
-1
(Pdb) p re.message
{u'status': 400, u'developerMessage': u'Login attempt failed because the specified password is incorrect.', u'message': u'Invalid username or password.', u'code': 7100, u'moreInfo': u'http://docs.stormpath.com/errors/7100'}
```

**Comment by avojnovicDk** [comment]
Hey, @arunabha! Thanks for reporting this issue and sorry for the delay.
`print(re)` and `print(re.message)` should print the same thing, but it should print only the `developerMessage` value. You should be able to access other values using error's attributes (`status`, `code`, `user_message`, `more_info`, ...).
However, sometimes `message` attribute contains the whole dict (like you reported), and other attributes are blank (or contains some default value). That is the bug I fixed in the above PR.

**Comment by rdegges** [comment]
I just merged this fix in, and will be cutting a release for this later today. Once the release is cut I'll post an update here an officially close this issue!

**Comment by rdegges** [comment]
Tests are running now =)

**Comment by rdegges** [comment]
Released!
