### ISSUE TITLE
Add DisabledCache Class

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#238]
We need a `DisabledCache` class that performs NO caching whatsoever. This has been a request from users for a while now, we should get this implemented once SAML is done with.

**Comment by rdegges** [comment]
Or maybe we name it `NoCache`, that might be nicer. Hmm.

**Comment by rdegges** [comment]
Or maybe `NullCache`, heh.

**Comment by jalsco** [comment]
just needed for customdata  -

**Comment by rdegges** [comment]
This is now implemented, so closing this issue.
