### ISSUE TITLE
Access Custom Data via Dot Notation

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#247]
Currently, custom data is lazily evaluated (which is great).

For instance, if I say:

```python
print account.custom_data['hi']
```

That will force the account object to fetch it's custom data from Stormpath, then print off the custom_data['hi'] value.

What isn't good, however, is that this functionality doesn't work as expected with dot notation. For instance:

```python
print account.custom_data.hi
```

This will simply evaluate to the empty dictionary `{}`, which is very confusing for users.

We should ensure that custom data can be referenced either via dot attributes, or via the existing array attributes.

I wrote a test, which is currently failing to assert this behavior: https://travis-ci.org/stormpath/stormpath-sdk-python/jobs/119314502

Hey @gcetusic, would you mind prioritizing this and making sure this test can pass?

**Comment by gcetusic** [comment]
@rdegges  On it!

**Comment by rdegges** [comment]
Closing as @gcetusic fixed this, and I've just merged his PR =)
