### ISSUE TITLE
IT tests should delete test data (applications, directories, etc)

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-python#249]
Lots of directories (thousands) with this prefix were recently purged from the testing tenant: https://github.com/stormpath/stormpath-sdk-python/blob/master/tests/live/base.py#L58

**Comment by rdegges** [comment]
Working on this. I'm refactoring some test stuff currently.

**Comment by rdegges** [comment]
Andddddd. Fixed! <3
