### ISSUE TITLE
PasswordGrantAuthenticator.authenticate causes KeyError when application's refresh token ttl set to 0

### ISSUE THREAD

**Issue by vasef** [stormpath/stormpath-sdk-python#261]
My Stormpath Applicaiton has refresh token ttl set to 0 days in its oAuth policy. 
When i try to use api_auth.PasswordGrantAuthenticator.authenticate(username,pwd), it raises KeyError. 

Possibly, this might be because there is no refresh token in the API response and the authenticate method tries to access it go generate PasswordAuthenticationResult.

**Comment by rdegges** [comment]
Hmm, thanks. I'll look into this :o
