### ISSUE TITLE
how do I get access to the user data in all routes using stormpath token based auth 

### ISSUE THREAD

**Issue by ohadperry** [stormpath/stormpath-sdk-python#263]
I'm trying to figure out token based auth. specifically in stormpath . 
1. client sign up
2. client logs in, get back a token. 
3. puts the token in the header of the following requests
4. server validates the token using stormpath api, and allows the user to enter the route. 

this token based vs session based is confusing. 
In The sessions based , i would do http://flask-stormpath.readthedocs.io/en/latest/product.html#access-user-data

```
from flask.ext.stormpath import login_required, user

@app.route('/email')
@login_required
def name():
    return user.email
```

How do I seamlessly have access to the user object in every route in token based ?
@rdegges

**Comment by vasifnawaz** [comment]
@ohadpartuck, 
http://stackoverflow.com/questions/37179915/flask-stormpath-token-based-authentication

**Comment by rdegges** [comment]
I'm going to close this for now, as this belongs in the Flask repo. We've already started working on this functionality. It'll be released relatively soon.
