### ISSUE TITLE
client_credentials grant flow needs to use the REST API

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-python#271]
Code written to support creating access tokens locally MUST use the REST API endpoint: https://stormpath.atlassian.net/browse/AM-2895

**Comment by rdegges** [comment]
https://stormpath.atlassian.net/wiki/display/AM/Token+Authentication+and+Management

**Comment by rdegges** [comment]
This is waiting on some stormpath fixes.
