### ISSUE TITLE
Local Validation sends a request to Stormpath

### ISSUE THREAD

**Issue by harai** [stormpath/stormpath-sdk-python#276]
The following code in `JwtAuthenticator` always sends a request to Stormpath server and spoils the advantage of Local Validation even if cache is enabled:

```
self.app.has_account(access_token.account)
```

https://github.com/stormpath/stormpath-sdk-python/blob/2.4.1/stormpath/api_auth.py#L584

**Comment by rdegges** [comment]
This is now merged. Release pending.
