### ISSUE TITLE
Support Validating OAuth Tokens Locally

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#280]

**Comment by fuxpavel** [comment]
would love to see this implemented

**Comment by rdegges** [comment]
This is now implemented!

**Comment by andremilk** [comment]
Any idea on when it will be released?

**Comment by rdegges** [comment]
This has been released as 2.5.0 on PyPI =)

**Comment by andremilk** [comment]
Thanks :)

**Comment by ronzilca** [comment]
Can you write a small example of this method? I can't find it in the docs.

**Comment by andremilk** [comment]
I believe that the only thing you need to do is to pass local_validation=True on the JwtAuthenticator.authanticate() method.

https://github.com/stormpath/stormpath-sdk-python/blob/master/stormpath/api_auth.py#L588

**Comment by rdegges** [comment]
This is correct.

**Comment by ronzilca** [comment]
Awesome, thank you

**Comment by ptone** [comment]
Time to update the docs ;)
https://docs.stormpath.com/python/product-guide/latest/auth_n.html#validating-the-token-locally
