### ISSUE TITLE
Test Resources Cleanup

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#312]
I've noticed that the reason tests are failing is that we're not cleaning up all the resources generated during testing.

@dinkom can you do some local testing and figure out what tests are leaving Stormpath resources behind? We should be cleaning up all resources created after each test run: applications, organizations, directories.

For some reason this isn't happening in some cases.

**Comment by dinkom** [comment]
@rdegges Sure, I'll figure it out.

**Comment by rdegges** [comment]
Thanks @dinkom for the awesome fix. <3
