### ISSUE TITLE
Redirect to new API reference

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-python#316]
Since this is the new API reference: https://docs.stormpath.com/python/apidocs/latest/
The http://stormpath.readthedocs.io/en/latest/stormpath.html version should be removed and redirect to the updated version. Right now, the read the docs version is showing up in most of my google searches :(

**Comment by rdegges** [comment]
Done.

**Comment by mdeggies** [comment]
Thanks! :)
