### ISSUE TITLE
Deprecate old docs

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-python#321]
Users are finding our old docs that don't include multi-tenancy and are getting confused. https://docs.stormpath.com/python/apidocs/index.html should redirect to the latest docs.

**Comment by rdegges** [comment]
Looking into this now... Hrm.

**Comment by rdegges** [comment]
Ok, took me a while to figure this one out. At first I thought this was an issue with the API docs themselves (it isn't). It looks like this is a bug in the stormpath.github.io repository.

Just fixed it in there, leaving this comment for future posterity.
