### ISSUE TITLE
AttributeError:  AuthToken has no attribute 'rsplit' trying to validate oauth token locally

### ISSUE THREAD

**Issue by kingcosmo** [stormpath/stormpath-sdk-python#326]
From this ticket it looks like we should be able to validate oauth tokens locally. 
https://github.com/stormpath/stormpath-sdk-python/issues/280

I can't find any documentation of how to do it.

Here is what I tried:

from stormpath.api_auth import PasswordGrantAuthenticator
from stormpath.api_auth import JwtAuthenticator
API_KEY_FILE = join(expanduser('~'), '.stormpath', 'apiKey.properties')

'''I had to add scheme='basic' ''' 
client = Client(api_key_file=API_KEY_FILE, scheme='basic')
application = client.applications.search({'name': 'mine'})[0]

authenticator = PasswordGrantAuthenticator(app=application)
result = authenticator.authenticate(login_user, login_pass)
account = result.account
token = result.stormpath_access_token

print("Validating Token")
jwt_auth = JwtAuthenticator(app=application)
jwt_result = jwt_auth.authenticate(token=token, local_validation=True )

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "./tornado-server.py", line 1050, in post
    jwt_result = jwt_auth.authenticate(token=token, local_validation=True )
  File "/usr/local/lib/python3.5/dist-packages/stormpath/api_auth.py", line 613, in authenticate
    return self._authenticate_with_local_validation(token)
  File "/usr/local/lib/python3.5/dist-packages/stormpath/api_auth.py", line 580, in _authenticate_with_local_validation
    access_token = AccessToken(self.app, token)
  File "/usr/local/lib/python3.5/dist-packages/stormpath/api_auth.py", line 97, in __init__
    data = jwt.decode(self.token, verify=False, algorithms=['HS256'])
  File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 58, in decode
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 135, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
  File "/usr/local/lib/python3.5/dist-packages/stormpath/resources/base.py", line 134, in __getattr__
    raise AttributeError("%s has no attribute '%s'" % (self.__class__.__name__, name))
AttributeError: AuthToken has no attribute 'rsplit'

**Comment by rdegges** [comment]
What version of our Python SDK are you using?

**Comment by kingcosmo** [comment]
>>> stormpath.__version__
'2.5.1'

**Comment by rdegges** [comment]
Thanks! Going to take a look at this.

**Comment by kingcosmo** [comment]
Do you suggest going back to an older version ?

**Comment by rdegges** [comment]
One thing you can try, when creating the Client(), is to pass: `scheme='basic'`.

EG:

```python
client = Client(id='xxx', secret='xxx', scheme='basic')
```

**Comment by kingcosmo** [comment]
I did already set scheme='basic' (see above)

**Comment by kingcosmo** [comment]
Ok, think I found it.  Your docs here https://docs.stormpath.com/python/product-guide/latest/auth_n.html#how-token-based-authentication-works   refer to result.stormpath_access_token  however that is not the object to pass when validating locally.  There is another object result.access_token.token  which works when passed to JwtAuthenticator.authenticate()

here is the working code.  I somehow figured this out by reading the test case code in test_api_auth.py :)

result = authenticator.authenticate(login_user, login_pass)

print("Validating Token")
jwt_auth = JwtAuthenticator(app=application)
jwt_result = jwt_auth.authenticate(result.access_token, local_validation=True )

**Comment by rdegges** [comment]
Going to close this since it is working. Will update the docs to show this.
